name: 'foodplanner'
version: '1.0.0'
config-version: 2

profile: 'default'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]


target-path: "target"  
clean-targets:         
    - "target"
    - "dbt_modules"

models:
  foodplanner_workshop:
    BRONZE:
      database: BRONZE
      raw:
        schema: FOODPLANNER_RAW
        materialized: table
        snowflake_warehouse: pc_dbt_wh
    silver:
      database: SILVER
      standardized:
        schema: FOODPLANNER
        materialized: view
        snowflake_warehouse: pc_dbt_wh
    # gold:
    #   +database: gold
    #   marts:
    #     +schema: marts
    #     +materialized: table
    #     +snowflake_warehouse: pc_dbt_wh_large
    # platinum:
    #   +database: platinum
    #   +materialized: table
    #   +snowflake_warehouse: pc_dbt_wh_large